version: '3.8'
services:
  vosk_cpu_worker:
    # restart: always
    deploy:
      mode: replicated
      replicas: 3
      #update_config:
      #  parallelism: 2
      #  delay: 2s
      #restart_policy:
      #  condition: on-failure
    volumes:
      - /mnt/share/audio_call/:/worker/audio/stereo
      - /mnt/share/audio_master/:/worker/audio/mono
      - ./vosk_cpu_worker/id_garden:/worker/id_garden
    build: vosk_cpu_worker
    environment:
      - WORKERS_COUNT=3
