sudo systemctl enable call_stt_0.service
sudo systemctl enable call_stt_1.service
sudo systemctl enable call_stt_2.service
sudo systemctl enable call_stt_3.service
sudo systemctl enable call_stt_4.service
sudo systemctl enable call_stt_5.service
sudo systemctl enable call_stt_6.service
sudo systemctl enable call_stt_7.service
sudo systemctl enable call_stt_8.service
sudo systemctl enable call_stt_9.service
sudo systemctl enable call_stt_10.service
sudo systemctl enable call_stt_11.service
sudo systemctl enable call_stt_12.service
sudo systemctl enable call_stt_13.service
sudo systemctl enable call_stt_14.service
sudo systemctl enable call_stt_queue.service
sudo systemctl enable call_stt_sentiment.service
