sudo systemctl stop call_stt_0.service
sudo systemctl stop call_stt_1.service
sudo systemctl stop call_stt_2.service
sudo systemctl stop call_stt_3.service
sudo systemctl stop call_stt_4.service
sudo systemctl stop call_stt_5.service
sudo systemctl stop call_stt_6.service
sudo systemctl stop call_stt_7.service
sudo systemctl stop call_stt_8.service
sudo systemctl stop call_stt_9.service
sudo systemctl stop call_stt_10.service
sudo systemctl stop call_stt_11.service
sudo systemctl stop call_stt_12.service
sudo systemctl stop call_stt_13.service
sudo systemctl stop call_stt_14.service
sudo systemctl stop call_stt_15.service
sudo systemctl stop call_stt_16.service
sudo systemctl stop call_stt_17.service
sudo systemctl stop call_stt_18.service
sudo systemctl stop call_stt_19.service
sudo systemctl stop call_stt_20.service
sudo systemctl stop call_stt_21.service
sudo systemctl stop call_stt_22.service
sudo systemctl stop call_stt_23.service
sudo systemctl stop call_stt_24.service
sudo systemctl stop call_stt_25.service
sudo systemctl stop call_stt_26.service
sudo systemctl stop call_stt_27.service
sudo systemctl stop call_stt_28.service
sudo systemctl stop call_stt_29.service
sudo systemctl stop call_stt_30.service
sudo systemctl stop call_stt_queue.service
#sudo systemctl stop call_stt_sentiment.service
